apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam
  template:
    metadata:
      labels:
        app: sam
    spec:
      containers:
      - image: okteto.dev/sam:latest
        name: sam
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "470806e7-3e23-43f3-9fd7-c4d66abd8416"
        - name: Vless_Path
          value: "/yy"
        - name: Vmess_UUID
          value: "470806e7-3e23-43f3-9fd7-c4d66abd8416"
        - name: Vmess_Path
          value: "/yu"
        - name: Share_Path
          value: "$Share_Path"
