apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bob
  template:
    metadata:
      labels:
        app: bob
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: bob
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "8dbdab9e-c355-4f50-96be-0ba57972d8bb"
        - name: Vless_Path
          value: "/aa"
        - name: Vmess_UUID
          value: "8dbdab9e-c355-4f50-96be-0ba57972d8bb"
        - name: Vmess_Path
          value: "/bb"
        - name: Share_Path
          value: "$Share_Path"
