apiVersion: apps/v1
kind: Deployment
metadata:
  name: baa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baa
  template:
    metadata:
      labels:
        app: baa
    spec:
      containers:
      - image: okteto.dev/baa:latest
        name: baa
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "d9a67a51-465a-4efe-8543-2de8adb7c2ed"
        - name: Vless_Path
          value: "/zx"
        - name: Vmess_UUID
          value: "d9a67a51-465a-4efe-8543-2de8adb7c2ed"
        - name: Vmess_Path
          value: "/xc"
        - name: Share_Path
          value: "$Share_Path"
