apiVersion: apps/v1
kind: Deployment
metadata:
  name: three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three
  template:
    metadata:
      labels:
        app: three
    spec:
      containers:
      - image: okteto.dev/three:latest
        name: three
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "573f4e0d-75a9-4a56-bd53-655e261ab8e8"
        - name: Vless_Path
          value: "/ga"
        - name: Vmess_UUID
          value: "573f4e0d-75a9-4a56-bd53-655e261ab8e8"
        - name: Vmess_Path
          value: "/gb"
        - name: Share_Path
          value: "$Share_Path"
