apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      labels:
        app: red
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: red
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "70a1099c-d718-47ee-ac92-5826d1e66aa3"
        - name: Vless_Path
          value: "/qq"
        - name: Vmess_UUID
          value: "70a1099c-d718-47ee-ac92-5826d1e66aa3"
        - name: Vmess_Path
          value: "/ww"
        - name: Share_Path
          value: "$Share_Path"
