apiVersion: apps/v1
kind: Deployment
metadata:
  name: kill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kill
  template:
    metadata:
      labels:
        app: kill
    spec:
      containers:
      - image: okteto.dev/wan:latest
        name: kill
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "ec6b65ed-fdc9-4ba1-821f-c8a565114380"
        - name: Vless_Path
          value: "/app"
        - name: Vmess_UUID
          value: "ec6b65ed-fdc9-4ba1-821f-c8a565114380"
        - name: Vmess_Path
          value: "/ssb"
        - name: Share_Path
          value: "$Share_Path"
