apiVersion: apps/v1
kind: Deployment
metadata:
  name: nana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nana
  template:
    metadata:
      labels:
        app: nana
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: nana
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "c4c7c011-bf01-46ad-adbb-f10465afe902"
        - name: Vless_Path
          value: "/pp"
        - name: Vmess_UUID
          value: "c4c7c011-bf01-46ad-adbb-f10465afe902"
        - name: Vmess_Path
          value: "/oo"
        - name: Share_Path
          value: "$Share_Path"
