apiVersion: apps/v1
kind: Deployment
metadata:
  name: foot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foot
  template:
    metadata:
      labels:
        app: foot
    spec:
      containers:
      - image: okteto.dev/foot:latest
        name: foot
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "4e28b762-4d71-4eb4-aed9-babb7be4154c"
        - name: Vless_Path
          value: "/123"
        - name: Vmess_UUID
          value: "4e28b762-4d71-4eb4-aed9-babb7be4154c"
        - name: Vmess_Path
          value: "/456"
        - name: Share_Path
          value: "$Share_Path"
