apiVersion: apps/v1
kind: Deployment
metadata:
  name: line
spec:
  replicas: 1
  selector:
    matchLabels:
      app: line
  template:
    metadata:
      labels:
        app: line
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: line
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "ba1d2019-5b52-4289-95cb-f753aa94321a"
        - name: Vless_Path
          value: "/cc"
        - name: Vmess_UUID
          value: "ba1d2019-5b52-4289-95cb-f753aa94321a"
        - name: Vmess_Path
          value: "/kk"
        - name: Share_Path
          value: "$Share_Path"
