apiVersion: apps/v1
kind: Deployment
metadata:
  name: wow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wow
  template:
    metadata:
      labels:
        app: wow
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: wow
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "185624b9-cf2e-4ee7-9cae-87e9a6de150d"
        - name: Vless_Path
          value: "/ss"
        - name: Vmess_UUID
          value: "185624b9-cf2e-4ee7-9cae-87e9a6de150d"
        - name: Vmess_Path
          value: "/mm"
        - name: Share_Path
          value: "$Share_Path"
