apiVersion: apps/v1
kind: Deployment
metadata:
  name: bite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bite
  template:
    metadata:
      labels:
        app: bite
    spec:
      containers:
      - image: okteto.dev/bite:latest
        name: bite
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "02e3f80b-bb88-48f9-82ff-9eca636a5ec8"
        - name: Vless_Path
          value: "/ki"
        - name: Vmess_UUID
          value: "02e3f80b-bb88-48f9-82ff-9eca636a5ec8"
        - name: Vmess_Path
          value: "/li"
        - name: Share_Path
          value: "$Share_Path"
