apiVersion: apps/v1
kind: Deployment
metadata:
  name: ban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ban
  template:
    metadata:
      labels:
        app: ban
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ban
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "f8238f0f-7ed6-4a08-a02d-4a66628f186f"
        - name: Vless_Path
          value: "/jj"
        - name: Vmess_UUID
          value: "f8238f0f-7ed6-4a08-a02d-4a66628f186f"
        - name: Vmess_Path
          value: "/hh"
        - name: Share_Path
          value: "$Share_Path"
