apiVersion: apps/v1
kind: Deployment
metadata:
  name: look
spec:
  replicas: 1
  selector:
    matchLabels:
      app: look
  template:
    metadata:
      labels:
        app: look
    spec:
      containers:
      - image: okteto.dev/look:latest
        name: look
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "cf762342-b36b-482a-a145-bf91161dfe8f"
        - name: Vless_Path
          value: "/eer"
        - name: Vmess_UUID
          value: "cf762342-b36b-482a-a145-bf91161dfe8f"
        - name: Vmess_Path
          value: "/aar"
        - name: Share_Path
          value: "$Share_Path"
