apiVersion: apps/v1
kind: Deployment
metadata:
  name: live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live
  template:
    metadata:
      labels:
        app: live
    spec:
      containers:
      - image: okteto.dev/live:latest
        name: live
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "c12a078e-8b01-4920-81e3-6fb8c23e8e06"
        - name: Vless_Path
          value: "/ba"
        - name: Vmess_UUID
          value: "c12a078e-8b01-4920-81e3-6fb8c23e8e06"
        - name: Vmess_Path
          value: "/ma"
        - name: Share_Path
          value: "$Share_Path"
