apiVersion: apps/v1
kind: Deployment
metadata:
  name: yan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yan
  template:
    metadata:
      labels:
        app: yan
    spec:
      containers:
      - image: okteto.dev/yan:latest
        name: yan
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "vumoo.to"
        - name: Vless_UUID
          value: "7daf9afc-9632-4989-9ca5-45cd0d48f3b7"
        - name: Vless_Path
          value: "/qwe"
        - name: Vmess_UUID
          value: "7daf9afc-9632-4989-9ca5-45cd0d48f3b7"
        - name: Vmess_Path
          value: "/rty"
        - name: Share_Path
          value: "$Share_Path"
